### ISSUE TITLE
Problem with .PAT file conversion

### ISSUE THREAD

**Issue by mhSepehri** [yoyoong/mHapSuite#3]
Hello, 
I converted a "test.pat" file using convert command without problem, it outputted "test.mhap.gz"
for indexing tabix did not work because of sorting so I used these commands:

`bgzip -d ./test.mhap.gz`
`cat ./test.mhap |sort -k1,1 -k2,2n | bgzip > ./test.mhap.gz`
`tabix -b 2 -e 3 ./test.mhap.gz`

And i got test.mhap.gz.tbi index file. Then I tried to run stat command :

`java -jar ./target/mHapSuite-2.0-jar-with-dependencies.jar stat -metrics MM PDR CHALM MHL MCR MBS Entropy R2 -mhapPath ./test/test.mhap.gz -cpgPath ./annotation/hg19_CpG.gz -bedPath ./test/panel.bed -outputFile ./test/stat.out.tsv -minK 1 -maxK 10 -K 4 -strand both -r2Cov 10
`

It worked fine for chr1 but when it reached to chr2 suddenly stopped and errored: 

> 2023-11-06 23:05:08.685 [main] INFO  com.Stat Region: chr1:247712238-247712240 calculate end!
> 2023-11-06 23:05:08.756 [main] INFO  com.Stat Region: chr1:247802889-247803176 calculate end!
> 2023-11-06 23:05:08.806 [main] INFO  com.Stat Region: chr1:248100586-248100615 calculate end!
> Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 10
        at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
        at java.base/java.lang.String.charAt(String.java:1515)
        at com.common.Util.getR2FromList(Util.java:403)
        at com.Stat.calculateNPairsAndR2(Stat.java:252)
        at com.Stat.getStat(Stat.java:189)
        at com.Stat.stat(Stat.java:68)
        at com.Main.main(Main.java:57)

I unziped, zipped and indexed one of your test data and it was fine so i was thinking maybe this problem comes from conversion of PAT files.  Can you help me solve this ?

**Comment by yoyoong** [comment]
I'm sorrry for a long time to answer this question. I wonder if the chromosome order of the cpg annotation file you are using is "chr1->chr2->chr3->..." instead of "chr1->chr10->chr11->..."? The mhapsuite versions less than 2.1 that chromosome order of the input cpg annotation file needs to be consistent with the pat file, and not required for versions after mhapsuite2.1.

**Comment by mhSepehri** [comment]
Thanks for the response. The problem is solved, and it was indeed due to sorting, but it was the BED file sorting, not the CpG annotation file.
